import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import "../styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-between">
        <Navbar />
        <section className="">{children}</section>
        <Footer />
      </body>
    </html>
  );
}
